### ISSUE TITLE
Connect Coreblocks to LiteX

### ISSUE THREAD

**Issue by tilk** [kuznia-rdzeni/coreblocks#223]
The task is to connect our core to the [LiteX framework](https://github.com/enjoy-digital/litex). This involves creating a `pythondata-cpu-coreblocks` module, which can then be used from inside LiteX. For example, see [pythondata-cpu-minerva](https://github.com/litex-hub/pythondata-cpu-minerva) and other existing modules.

**Comment by piotro888** [comment]
https://github.com/kuznia-rdzeni/litex and https://github.com/kuznia-rdzeni/pythondata-cpu-coreblocks
