### ISSUE TITLE
Migrate to Data type

### ISSUE THREAD

**Issue by lekcyjna123** [kuznia-rdzeni/coreblocks#237]
RFC with Data types have been merged, so we can migrate on it.
https://github.com/amaranth-lang/rfcs/pull/1

**Comment by tilk** [comment]
Removed the "Priority" label and swapped for "Nice to have". We kind of settled on records, and work around most of their limitations.  Amaranth's data types functionality is fresh, bugs are to be expected, the limitations are unknown, also the functionality is evolving (see e.g. https://github.com/amaranth-lang/rfcs/pull/8 and https://github.com/amaranth-lang/rfcs/pull/11). I'd wait a little before attempting to switch.

**Comment by whitequark** [comment]
> I'd wait a little before attempting to switch.

Agreed; I would suggest you wait before the next release.

**Comment by whitequark** [comment]
> We kind of settled on records

Note that Records will be removed with a 1-version deprecation cycle (so probably before the end of this year).

**Comment by tilk** [comment]
> Note that Records will be removed with a 1-version deprecation cycle (so probably before the end of this year).

Thanks for the heads-up. Do you recommend that we still wait for the next release to work on an alternative solution (using amaranth.lib.data), or is it better to start ASAP?

**Comment by whitequark** [comment]
`amaranth.lib.data` should be in its final form now. I would recommend starting to work on it ASAP, and any bugs or issues you find as you start using it are most welcome as reports since we have the most flexibility to amend it before it appears in a release.

**Comment by whitequark** [comment]
Also, nothing technically stops you from copying `amaranth.hdl.rec` to your own codebase and continuing to use it, as it does not integrate with core Amaranth directly, only using public APIs.

**Comment by tilk** [comment]
> Also, nothing technically stops you from copying `amaranth.hdl.rec` to your own codebase and continuing to use it, as it does not integrate with core Amaranth directly, only using public APIs. It's just very poorly designed.

Yes, yes it is. We did some lot to work around the deficiencies. For example see this function, which allows to assign fields, with error checking, between records and dicts with signals, and more: https://github.com/kuznia-rdzeni/coreblocks/blob/739b1235c73230725fece3d27ad05c0203da942b/coreblocks/utils/utils.py#L146
