### ISSUE TITLE
Add timeout for github verification

### ISSUE THREAD

**Issue by lekcyjna123** [kuznia-rdzeni/coreblocks#300]
We should add timeout in github verification to prevent of burning computation minutes in case of loops in simulations. As for now in case of errors jobs can run more than 5h which is way too long:
https://github.com/kuznia-rdzeni/coreblocks/actions/runs/4777452613

**Comment by tilk** [comment]
This is probably the right way to to do it:
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idtimeout-minutes
