### ISSUE TITLE
Add support for branch speculation

### ISSUE THREAD

**Issue by lekcyjna123** [kuznia-rdzeni/coreblocks#419]
To use whole potential of out-of-order execution we need a speculation over jumps. As for now we stall whole pipeline till branch is retired. Instead of that we should:
- have a branch predictor
- check in fetch if fetched instruction is jump - if yes:
  - use branch predictor to get next_pc
  - make a checkpoint of current CPU state
- on mispredicted branch CPU state from before speculation should be restored and execution should be started from that point

Comments:
- first branch predictor can be very easy e.g. always `current_pc+4`
- if this will make a task easier we can assume speculation depth = 1

**Comment by tilk** [comment]
@lekcyjna123 Could you write a proper description?

**Comment by lekcyjna123** [comment]
Description has been updated

**Comment by piotro888** [comment]
link (not closing) #557

**Comment by tilk** [comment]
Shouldn't this be closed already? If you believe not, please write the reason.
