### ISSUE TITLE
[Interrupts] Stall implementation for UnalignedFetch

### ISSUE THREAD

**Issue by Kristopher38** [kuznia-rdzeni/coreblocks#431]
This is an issue for `feature/interrupts` branch. UnalignedFetch comes without `stall` method which is vital for interrupts to work at all. Unfortunately [doing this naively](https://github.com/kuznia-rdzeni/coreblocks/blob/feature/interrupts/coreblocks/frontend/fetch.py#L238) fails under some circumstances so a more detailed approach is needed. Currently a [workaround](https://github.com/kuznia-rdzeni/coreblocks/blob/feature/interrupts/coreblocks/params/configurations.py#L135) is used which forces the use of standard fetch (core runs without C extension) just for running the tests. Goals here are:
- write a proper (preferably tested) stall method for UnalignedFetch
- remove the mentioned workaround

**Comment by tilk** [comment]
Looks like this is no longer an issue.
