### ISSUE TITLE
Add tests for RAT

### ISSUE THREAD

**Issue by lekcyjna123** [kuznia-rdzeni/coreblocks#475]
There is no unit tests for RAT class (coreblocks/struct_common/rat.py). Please add them.

**Comment by Kristopher38** [comment]
I'd like to point out that FRAT and RRAT are being explicitly tested as part of testing other components, they just don't have their dedicated unit tests - the former is tested inside the scheduler test (see [here](https://github.com/kuznia-rdzeni/coreblocks/blob/master/test/scheduler/test_scheduler.py#L310) and the latter is tested in the retirement test (see [here](https://github.com/kuznia-rdzeni/coreblocks/blob/master/test/stages/test_retirement.py#L110))
