### ISSUE TITLE
[RFC] Proposition to clean up coreblocks

### ISSUE THREAD

**Issue by lekcyjna123** [kuznia-rdzeni/coreblocks#571]
Hi,
as agreed on the last meeting, here is a proposition with new structure of directories in coreblocks:

- coreblocks
  - frontend (as is)
  - lsu (as is)
  - fu
    - csr_unit.py (part of csr.py)
  - control
    - csr_register.py (part of csr.py)
    - csr_instances.py (now csr_generic.py)
    - exception.py
    - instr_counter.py
    - interrupt_controler.py
  - structs_common (all which has now and isn't moved to control)
  - core_constructors (alternatives: core_builder, core_abstractions)
    - rs_func_block.py
    - func_blocks_unifier.py
  - <place_holder> (propositions: ender, commiter, cleaner, arch_state_organizer, deoutoforderer)
    - announcement.py
    - retirement.py
  - layouts
  - constants
    - isa.py
    - optypes.py
  - utils
    - keys.py
    - instr.py
- constants
  - core_topologies.py (hardcoded configurations from params/configurations.py)

**Comment by piotro888** [comment]
And as promised, my proposition:
```
coreblocks/
    frontend/
        decoder/
            isa.py (only enums from isa.py)
            optypes.py
        fetch/
    func_blocks/
        interface/
            func_protocols.py (now utils/protocols.py)
            func_blocks_unifer.py
        csr/
        lsu/
        fu/
            common/ (or maybe it can be merged with func_blocks/interface/ as func_blocks/common/)
                fu_decoder.py
                rs.py
                rs_func_block.py
            alu, div, ...
    scheduler/
    backend/
        annoucement/ (current backend/)
        retirement/
    core_structs/
        rat.py rob.py rf.py
    priv/
        structs/
            exception.py
            instr_counter.py
            interrupt_controller.py
        csr/
            csr_register.py
            csr_instances.py
    layouts/
    params/
        core_configurations.py
        genparams.py
        icache_params.py
        fu_params.py
        isa_params.py (only ISA class)
        keys.py (?, maybe somehow together with layouts?)
```
It think that we should wait until next meeting, to discuss how to merge best parts of both propositions
