### ISSUE TITLE
pytest fixtures are executed multiple times

### ISSUE THREAD

**Issue by xThaid** [kuznia-rdzeni/coreblocks#675]
Fixtures like `configure_profiles` and `configure_logging` from `TestCaseWithSimulator` are called for every test function in a test class. As a result, for example multiple logging handlers are added and logs are printed many times.

**Comment by Kristopher38** [comment]
Solution: add `scope="session"` to fixture, see: https://docs.pytest.org/en/7.1.x/how-to/fixtures.html#scope-sharing-fixtures-across-classes-modules-packages-or-session
