### ISSUE TITLE
Bit-vector free RF list with superscalarity

### ISSUE THREAD

**Issue by tilk** [kuznia-rdzeni/coreblocks#697]
Using `MultiPriorityEncoder` from #573, one could implement a clean free RF list with superscalarity support. If I see correctly, this is already implemented in #395. (Everything is already implemented there, apparently.)

**Comment by piotro888** [comment]
it will be also needed soon for checkpointing implementation

**Comment by tilk** [comment]
Transactron now has a PriorityEncoderAllocator, which could be used as a free register set.
